In [30]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [31]:
iris = pd.read_csv("../datasets/Iris.csv")

In [32]:
iris.shape

(150, 7)

In [33]:
iris.loc[5]

Id                         6
SepalLengthCm            5.4
SepalWidthCm             3.9
PetalLengthCm            1.7
PetalWidthCm             0.4
Species          Iris-setosa
Species_1                  0
Name: 5, dtype: object

In [34]:
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
 6   Species_1      150 non-null    int64
dtypes: float64(4), int64(2), str(1)
memory usage: 8.3 KB

In [35]:
iris.iloc[0:5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species_1
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0

In [36]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
Species_1        0
dtype: int64

In [ ]:
iris["PetalLengthCm"].unique()

np.float64(181.5)

In [46]:
iris["PetalLengthCm"].value_counts()

PetalLengthCm
1.5    14
1.4    12
4.5     8
5.1     8
1.3     7
1.6     7
5.6     6
4.7     5
4.9     5
4.0     5
1.7     4
4.2     4
4.4     4
4.8     4
5.0     4
4.6     3
3.9     3
4.1     3
5.8     3
6.1     3
5.5     3
5.7     3
1.2     2
1.9     2
3.3     2
3.5     2
4.3     2
6.0     2
5.9     2
5.3     2
6.7     2
5.4     2
5.2     2
1.1     1
1.0     1
3.6     1
3.8     1
3.7     1
3.0     1
6.6     1
6.3     1
6.9     1
6.4     1
Name: count, dtype: int64

In [49]:
x = iris.drop('Species',axis=1)
x

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species_1
0      1            5.1           3.5            1.4           0.2          0
1      2            4.9           3.0            1.4           0.2          0
2      3            4.7           3.2            1.3           0.2          0
3      4            4.6           3.1            1.5           0.2          0
4      5            5.0           3.6            1.4           0.2          0
..   ...            ...           ...            ...           ...        ...
145  146            6.7           3.0            5.2           2.3          2
146  147            6.3           2.5            5.0           1.9          2
147  148            6.5           3.0            5.2           2.0          2
148  149            6.2           3.4            5.4           2.3          2
149  150            5.9           3.0            5.1           1.8          2

[150 rows x 6 columns]

In [54]:
iris.columns.value_counts()

Id               1
SepalLengthCm    1
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     1
Species          1
Species_1        1
Name: count, dtype: int64